version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run:
          command: npm install
          name: install
      - run:
          command: npm test
          name: test
workflows:
  version: 2.0
  build:
    jobs:
      - build